name: CI

on:
  pull_request:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: './src/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint code for consistent style
        run: yarn lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: './src/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check TypeScript types
        run: yarn type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: './src/yarn.lock'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:unit